spring:
  profiles:
    active: @spring.profiles.active@

  # Database
  datasource:
    username: postgres
    password: root1234
    url: jdbc:postgresql://decorate.csjuggemk0ut.eu-central-1.rds.amazonaws.com:5432/decorate
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

  mail:
    host: "smtp.mailtrap.io"
    port: 2525
    ssl: no
    tls: yes
    username: "2c09225ea19cd0"
    password: "d06a0abade0cb1"
    protocol: "smtp"

logging:
  level:
    hu.formulative.demo: debug
    org.springframework.web: info
    org.hibernate: info
  pattern:
    console: "%cyan(%d{yyyy-MM-dd HH:mm:ss}) [%green(%thread)] %highlight(%-5level) %yellow(%logger{36}) - %msg%n"


server:
  port: 5000







